[package]
name = "alternator-driver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
aws-sdk-dynamodb = { version = "1.100.0", features = ["test-util"] }
itertools = "0.14.0"
reqwest = { version = "0.11", features = ["json"] }


[dev-dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "1.8", features = ["client", "server", "http1"] }
http = "1.0"
http-body-util = "0.1"
hyper-util = "0.1"
futures = "0.3.31"
uuid = { version = "1", features = ["v4"] }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(ccm_tests)',
] }
